### ISSUE TITLE
jsfiddle.net doesn't work in Chrome Canary 44 for MacOS

### ISSUE THREAD

**Issue by fr0** [jsfiddle/jsfiddle-issues#595]
It gets stuck on the "Initializing the awesome!" screen, and I have the following JavaScript errors:

Uncaught TypeError: Number.prototype.valueOf is not generic
Sidebar.js:4 Uncaught ReferenceError: Class is not defined
LayoutCM.js:299 Uncaught ReferenceError: Events is not defined
Actions.js:5 Uncaught TypeError: Cannot read property 'implement' of undefined
Resources.js:133 Uncaught TypeError: window.addEvent is not a function
EditorCM.js:17 Uncaught ReferenceError: Class is not defined
Settings.js:5 Uncaught ReferenceError: Class is not defined
jsfiddle.net/:73 Uncaught TypeError: Cannot read property 'read' of undefined
jsfiddle.net/:227 Uncaught TypeError: window.addEvent is not a function
jsfiddle.net/:818 Uncaught TypeError: window.addEvent is not a function

The site works fine in Chrome Version 41.0.2272.118 (64-bit).

**Comment by oskarkrawczyk** [comment]
Canary is too bleeding edge to test production stuff on.
